version: '2'

services:  
  proxy:
    restart: always
    # build:
    #   context: ./nginx/
    #   dockerfile: Dockerfile
    image: nginx
    hostname: proxy
    ports:
      - "80:80"
    depends_on:
      - web
  # PostgreSQL database
  db:
    image: postgres

  # Django web server
  web:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: web
    command: /app/sitat/run_web.sh
    # volumes:
    #   - .:/app
    ports:
      - "9000:9000"
    links:
      - db
    depends_on:
      - db